name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pyyaml
  - hydra-core=1.3.2  
  - setuptools<81
  - importlib_resources
  - pip
  - pip:
      - mlflow==2.8.1      
      - hydra-joblib-launcher==1.1.2
