main:
  components_repository: "https://github.com/CloudiusAurelius/ml-scoring-monitoring"
  # All the intermediate files will be copied to this directory at the end of the run.
  # Set this to null if you are running in prod
  project_name: ml_scoring_monitoring
  experiment_name: development
  steps: all
data_ingestion:
  config_file: "config.json"
  output_filename: "finaldata.csv"
model_training:
  config_file: "config.json"
  output_modelname: "trainedmodel.pkl"
model_scoring:
  config_file: "config.json"
  input_data: "finaldata.csv"
  input_modelinfo: "trainedmodel.pkl"
  output_score_filename: "latestscore.txt"
