name: ml_scmon
channels:
  - conda-forge
  - defaults
dependencies:  
  - jupyter  
  - jupyterlab  
  - scikit-learn  
  - pandas
  - numpy    
  - fastapi   
  - requests
  - pytest  
  - pip
  - pip:
    - logging
    - mlflow
