name: data_ingestion
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip  
  - pandas
  - numpy=1.23.5  
  - scikit-learn
  - matplotlib
  - seaborn
  - pip:
      - mlflow==2.8.1

